version: "3.8"

services:
    backend:
        build:
            context: ./backend
        ports:
            - "15696:15696"
        environment:
            - NODE_ENV=production

    # frontend:
    #     build:
    #         context: ./frontend
    #     ports:
    #         - "5000:5000"
    #     depends_on:
    #         - backend
